// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIYm3YnGPyyQooS5qwI9t78fEc2KkD7h0',
    appId: '1:214769553814:web:28e26477b5d169dbddcdb7',
    messagingSenderId: '214769553814',
    projectId: 'questime-project-beta',
    authDomain: 'questime-project-beta.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0jONn0aSeVYhi-oub7c-iwtPgOdjwcA',
    appId: '1:214769553814:android:16bd8f60fc17a1d0ddcdb7',
    messagingSenderId: '214769553814',
    projectId: 'questime-project-beta',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwyEYHAE8brh7Dy4OgA8zd3AZdQA_Rdv0',
    appId: '1:214769553814:ios:49b0c51c08c7dfc9ddcdb7',
    messagingSenderId: '214769553814',
    projectId: 'questime-project-beta',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwyEYHAE8brh7Dy4OgA8zd3AZdQA_Rdv0',
    appId: '1:214769553814:ios:49b0c51c08c7dfc9ddcdb7',
    messagingSenderId: '214769553814',
    projectId: 'questime-project-beta',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIYm3YnGPyyQooS5qwI9t78fEc2KkD7h0',
    appId: '1:214769553814:web:8505d7d4771c3d28ddcdb7',
    messagingSenderId: '214769553814',
    projectId: 'questime-project-beta',
    authDomain: 'questime-project-beta.firebaseapp.com',
  );

}